### attempt login for valid user
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "test4",
  "password": "test"
}

### attempt login for valid user with wrong password
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "test4",
  "password": "whatcoulditbe"
}