### attempt login for valid user
POST https://city-search-node-api.herokuapp.com/login
Content-Type: application/json

{
  "username": "test13",
  "password": "test"
}

### attempt login for valid user
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "hi",
  "password": "hi"
}

### attempt login for valid user with wrong password
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "test4",
  "password": "whatcoulditbe"
}