### create a valid user
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "test4",
  "password": "test"
}

### create a valid user
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "test2",
  "password": "tes!t"
}

### invalid username
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "tes!t",
  "password": "test"
}

### invalid password
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "test3",
  "password": "tes t"
}
