### create a valid user
POST https://city-search-node-api.herokuapp.com/register
Content-Type: application/json

{
  "username": "hi",
  "password": "hi"
}

### create a valid user
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "hi",
  "password": "hi"
}

### invalid username
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "tes!t",
  "password": "test"
}

### invalid password
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "test3",
  "password": "tes t"
}
