export enum ExceptionCodes {
    GENERIC_INTERNAL = 'IER001',
    
    FULL_COORDINATES_ARE_MANDATORY_EXCEPTION = 'SUGGESTIONS001',

    ENVIRONMENT_VARIABLE_NOT_FOUND = 'ENVVARNOTFOUND',
    
    MISSING_FILED_OR_INVALID_TYPE = 'VALIDATION001',

}