language: node_js
node_js:
- '0.10'
services:
- mongodb
before_script:
- mongoimport -d cities -c cities --file ./data/cities_canada-usa.tsv --type tsv --headerline
deploy:
  provider: heroku
  api_key:
    secure: aJVVrgawss5gUI6HpNSwPAfQNeLtbgWY5E3mPsfjrVl9wWGMr2HiqrGhxbs7OQ3P3lte+/D1HA085iDUP9Etz2IQ3TCoF5S5pvXLA80fbJn4y+MakxkNCsjLb6BXzHzjE002nyoYlPlJR5RuAoS8dCNLlRMgf/ssj9LCJ+MnVDo=
  app: busbud-suggestions
  on:
    repo: stealth-coaxial/coding-challenge-backend-c
