version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
    networks:
      - overlay
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    networks:
      - overlay
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      cache_from:
        - node:12
      args:
        - CODE_VERSION=0.1
    env_file:
      - .env
    ports:
      - 2345:2345
    networks:
      - overlay
    depends_on:
      - elasticsearch
networks:
  overlay:

volumes:
  es_data:
