version: '3.5'

services:
    db:
        image: postgres:14.2
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - '5432:5432'

    web:
        build: ./docker/web
        ports:
            - "2345:2345"
        working_dir: /var/www/busbud
        volumes:
            - .:/var/www/busbud
        depends_on:
            - db
