FROM node:14.17.1-alpine3.11 as base
ENV NODE_ENV development

WORKDIR /usr/src/app

RUN apk add --no-cache tini

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .
COPY --chown=node:node .env.docker .env

USER node

EXPOSE 2345

FROM base as test
ENTRYPOINT ["/sbin/tini", "--" , "npm", "run", "test"]

FROM base as dev
ENTRYPOINT ["/sbin/tini", "--" , "npm", "run", "start.dev"]
