version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: suggestions-es
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  redis:
    image: redis:latest
    container_name: suggestions-cache-redis
    ports:
      - 6379:6379

volumes:
  elasticsearch-data:
