version: '3'
services:
  redis:
    image: redis:5.0-alpine
    env_file:
      - .env
    volumes: 
      - redis-data:/data
    entrypoint: 'redis-server --appendonly yes'
  api:
      build:
        context: .
        dockerfile: docker/api/Dockerfile
      env_file:
        - .env  
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - 80:2345
        - 9229:9229
      links:
        - mongo
        - redis
      command: npm run dev
  mongo:
      image: 'bitnami/mongodb:4.1'
      ports:
        - "27017:27017"
      env_file:
        - .env
      volumes:
        - 'mongo-data:/bitnami'
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      env_file:
        - .env
volumes:
  mongo-data:
  redis-data:
