version: '3.8'

services:
  app:
    container_name: busbud-challenge-app
    build:
      context: docker-compose/app
    ports:
      - ${DOCKER_APP_PORT}:3000
    volumes:
      - .:/home/node/busbud-challenge
      - ${SSH_DIR}:/home/node/.ssh
    environment:
      - DOCKER_APP_CONTAINER=1

  postgres:
    container_name: busbud-challenge-postgres
    image: postgres:14.2-alpine
    ports:
      - ${DOCKER_POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  redis:
    container_name: busbud-challenge-redis
    image: redis:7.0-alpine
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
