FROM centos:7.6.1810

RUN yum -y groupinstall 'Development Tools' && \
  yum -y install openssl-devel git

RUN git clone https://github.com/giltene/wrk2.git && \
  cd wrk2 && \
  make && \
  cp wrk /bin/
