module.exports = {
    US: {
        AR: 'Arkansas',
        DC: 'Washington, D.C.',
        DE: 'Delaware',
        FL: 'Florida',
        GA: 'Georgia',
        KS: 'Kansas',
        LA: 'Louisiana',
        MD: 'Maryland',
        MO: 'Missouri',
        MS: 'Mississippi',
        NC: 'North Carolina',
        OK: 'Oklahoma',
        SC: 'South Carolina',
        TN: 'Tennessee',
        TX: 'Texas',
        WV: 'West Virginia',
        AL: 'Alabama',
        CT: 'Connecticut',
        IA: 'Iowa',
        IL: 'Illinois',
        IN: 'Indiana',
        ME: 'Maine',
        MI: 'Michigan',
        MN: 'Minnesota',
        NE: 'Nebraska',
        NH: 'New Hampshire',
        NJ: 'New Jersey',
        NY: 'New York',
        OH: 'Ohio',
        RI: 'Rhode Island',
        VT: 'Vermont',
        WI: 'Wiscousin',
        CA: 'California',
        CO: 'Colorado',
        NM: 'New Mexico',
        NV: 'Nevada',
        UT: 'Utah',
        AZ: 'Arizona',
        ID: 'Idaho', 
        MT: 'Montana',
        ND: 'North Dakota',
        OR: 'Oregon',
        SD: 'South Dakota',
        WA: 'Washington',
        WY: 'Wyoming',
        HI: 'Hawaii',
        AK: 'Alaska',
        KY: 'Kentucky',
        MA: 'Massachusetts',
        PA: 'Pennsylvania',
        VA: 'Virginia'
    },
    CA: {
       '01': 'AB',
       '02': 'BC',
       '03': 'MB',
       '04': 'NB',
       '05': 'NL',
       '07': 'NS',
       '08': 'ON',
       '09': 'PE',
       '10': 'QC',
       '11': 'SK',
       '12': 'YT',
       '13': 'NT',
       '14': 'NU'
    }
}
