#!/usr/bin/env bash

set -e

if [ -z ${REL_NAME+x} ]; then echo "REL_NAME is unset"; exit 1; fi

RELEASE=rel/${REL_NAME}

# strip symbol information out of any ERTS binaries
for fat in $(file rel/*/erts-*/bin/*|grep "not stripped"|awk '{print $1}'|cut -d: -f1); do
    strip $fat &>/dev/null;
done

# copy any dynamically linked libaries used by ERTS into release
for lib in $(ldd rel/*/erts-*/bin/* rel/*/erts-*/lib/* rel/*/lib/*/priv/lib/* rel/*/lib/*/priv/bin/* $(which sh) 2>/dev/null|grep "=> /"|awk '{print $3}'|sort|uniq); do
    mkdir -p $(dirname ${RELEASE}$lib)
    cp -Lv $lib ${RELEASE}$lib
done

# ensure that the link loader is present
mkdir -p ${RELEASE}/lib64
cp /lib64/ld-linux*.so.* ${RELEASE}/lib64

# and a shell
cp /bin/sh ${RELEASE}/bin/sh
